/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\8_FindKaguya\Shader\Voxel_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter;"
 "uniform int _MapIndex;"
 "uniform float _Alpha;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.0003\n"
 "#define tmax 30.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\n"
 "vec3 e;"
 "int v;struct mapr{float d;bool hit;int m;vec3 vPos;vec3 mask;};"
 "void f(inout mapr v,float d,int m,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,m,vec3(0.),vec3(0.));"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,m,vec3(0.),vec3(0.));"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 t(vec3 v,vec3 m,vec3 d,vec3 x)"
 "{"
   "return v+=x,v.yz*=rot(m.x),v.xz*=rot(m.y),v.xy*=rot(m.z),v*=m,v;"
 "}"
 "vec2 f(float v)"
 "{"
   "float m=sin(v*.11),x=cos(v*.14);"
   "return vec2(m*4.-x*1.5,x*1.7+m*1.5);"
 "}"
 "float t(vec2 v)"
 "{"
   "return fract(sin(dot(v,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float n(vec3 v)"
 "{"
   "v.xy-=f(v.z);"
   "v=cos(v*.1575+sin(v.zxy*.4375));"
   "float x=dot(v,v);"
   "v=sin(v*3.+cos(v.yzx*3.));"
   "return x-v.x*v.y*v.z*.35-.9;"
 "}"
 "float s(vec3 v)"
 "{"
   "v.xz=vec2(atan(v.x,v.z)/3.*pi,length(v.xz)-1.);"
   "v=cos(v*.1575+sin(v.zxy*.4375));"
   "float x=dot(v,v);"
   "return x-v.x*v.y*v.z*.35-.9;"
 "}"
 "mapr m(vec3 v)"
 "{"
   "mapr m;"
   "m.d=1e3;"
   "m.hit=false;"
   "m.m=-1;"
   "if(_MapIndex==0)"
     "f(m,n(v),0,true);"
   "if(_MapIndex==1)"
     "f(m,s(v),0,true);"
   "return m;"
 "}"
 "vec3 x(vec3 v)"
 "{"
   "vec2 x=vec2(.001,0.);"
   "return normalize(vec3(m(v+x.xyy).d-m(v-x.xyy).d,m(v+x.yxy).d-m(v-x.yxy).d,m(v+x.yyx).d-m(v-x.yyx).d));"
 "}"
 "mapr f(vec3 v,vec3 x,const bool d)"
 "{"
   "vec3 f=floor(v)+.5;"
   "mapr i;"
   "vec3 s=1./abs(x);"
   "x=sign(x);"
   "vec3 a=s*(x*(f-v)+.5),r=vec3(0.);"
   "int e=d?40:80;"
   "for(int b=0;b<e;b++)"
     "{"
       "if((i=m(f)).d<0.)"
         "break;"
       "r=step(a,a.yzx)*(1.-step(a.zxy,a));"
       "a+=r*s;"
       "f+=r*x;"
     "}"
   "i.vPos=f;"
   "i.mask=r;"
   "return i;"
 "}"
 "float m(vec3 v,vec3 x,float a)"
 "{"
   "vec3 i=floor(v)+.5,s=1./abs(x);"
   "x=sign(x);"
   "vec3 f=s*(x*(i-v)+.5),r=vec3(0);"
   "float d=1.;"
   "for(int b=0;b<16;b++)"
     "{"
       "d=m(i).d;"
       "if(d<0.||length(i-v)>a)"
         "break;"
       "r=step(f,f.yzx)*(1.-step(f.zxy,f));"
       "f+=r*s;"
       "i+=r*x;"
     "}"
   "return 1.=step(0.,d)*.7+.3;"
 "}"
 "vec4 n(vec3 v,vec3 x,vec3 a)"
 "{"
   "vec4 f=vec4(m(v+x).d,m(v+a).d,m(v-x).d,m(v-a).d),i=vec4(m(v+x+a).d,m(v-x+a).d,m(v-x-a).d,m(v+x-a).d);"
   "f=step(f,vec4(0));"
   "i=step(i,vec4(0));"
   "return 1.-(f+f.yzwx+max(i,f*f.yzwx))/3.;"
 "}"
 "float m(vec3 v,vec3 x,vec3 a,vec3 m)"
 "{"
   "vec4 f=n(v-sign(a)*m,m.zxy,m.yzx);"
   "x=fract(x);"
   "vec2 i=x.yz*m.x+x.zx*m.y+x.xy*m.z;"
   "return mix(mix(f.z,f.w,i.x),mix(f.y,f.x,i.x),i.y);"
 "}\n"
 "#define MM 0\n"
 "float i=.5,d=1.,c=3.,z=1.,y=.67,a=1.,k=50.,r=0.;"
 "vec3 p(uvec3 v)"
 "{"
   "\n#define scramble x=( (x>>8U)^x.yzx)*1103515245U\n"
   "scramble;"
   "scramble;"
   "scramble;"
   "return vec3(v)/float(-1U);"
 "}\n"
 "#define hash22(pvalue)fract( 18.5453*sin( pvalue*mat2(127.1,311.7,269.5,183.3)))\n"
 "#define disp(pvalue)(-ofs+(1.+2.*ofs)*hash22(pvalue))\n"
 "vec3 h(vec2 v)"
 "{"
   "vec2 x=floor(v),m,a;"
   "float d=1e9,f;"
   "for(int i=0;i<25;i++)"
     "{"
       "vec2 s=x+vec2(i%5-2,i/5-2),r=disp(s),e=s-v+r;"
       "f=dot(e,e);"
       "if(f<d)"
         "d=f,m=s-x,a=e;"
     "}"
   "d=1e9;"
   "for(int i=0;i<25;i++)"
     "{"
       "vec2 s=x+m+vec2(i%5-2,i/5-2),r=disp(s),e=s-v+r;"
       "if(dot(a-e,a-e)>1e-5)"
         "d=min(d,.5*dot(a+e,normalize(e-a)));"
     "}"
   "return vec3(d,a+v);"
 "}\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "int b=1;\n"
 "#define hash21(pvalue)fract(sin(dot(pvalue,vec2(127.1,311.7)))*43758.5453123)\n"
 "float w(vec2 v)"
 "{"
   "vec2 x=floor(v),f=fract(v);"
   "f=f*f*(3.-2.*f);"
   "float s=mix(mix(hash21(x+vec2(0,0)),hash21(x+vec2(1,0)),f.x),mix(hash21(x+vec2(0,1)),hash21(x+vec2(1,1)),f.x),f.y);"
   "return b==0?s:b==1?2.*s-1.:b==2?abs(2.*s-1.):1.-abs(2.*s-1.);"
 "}\n"
 "#define noise22(pvalue)vec2(noise2(pvalue),noise2(pvalue+17.7))\n"
 "vec2 l(vec2 v)"
 "{"
   "vec2 x=vec2(0);"
   "float m=.5;"
   "mat2 d=rot(.37);"
   "for(int i=0;i<6;i++,v*=2.,m/=2.)"
     "v*=d,x+=m*noise22(v);"
   "return x;"
 "}"
 "vec3 u(vec2 v)"
 "{"
   "vec3 x,f=vec3(0.);"
   "for(float i=0.;i<c;i++)"
     "{"
       "vec2 m=v/vec2(d,1),e=y*l(v/z)*z;"
       "vec3 s=h(m+e);"
       "if(i==0.)"
         "x=s;"
       "float b=s.x;"
       "b=min(1.,k*pow(max(0.,b-r),a));"
       "f+=vec3(1.-b)/exp2(i);"
       "v*=1.5*rot(.37);"
     "}"
   "return f;"
 "}"
 "float h(vec3 v,vec3 x,float d,float a)"
 "{"
   "const float i=6.;"
   "float f=0.;"
   "for(float e=1.;e<i+.5;e++)"
     "{"
       "float s=(e*.75+fract(cos(e)*45758.5453)*.25)/i*d;"
       "f+=(s+m(v-x*s).d)/pow(1.+s,a);"
     "}"
   "return clamp(1.-f/i,0.,1.);"
 "}"
 "vec3 f(vec3 v,vec3 x,float d,mapr f,vec3 s,const bool a)"
 "{"
   "vec3 i=vec3(0.);"
   "if(f.hit)"
     "{"
       "vec3 e=v+x*d,y=-(f.mask*sign(x));"
       "if(f.m==0)"
         "{"
           "vec3 r=s-e;"
           "float z=max(length(r),.001);"
           "r/=z;"
           "float b=1./(1.+z*.2+z*.1),t=m(e+y*.01,r,z),k=m(f.vPos,e,x,f.mask),c=max(0.,dot(y,r)),n=pow(max(0.,dot(reflect(-r,y),-x)),32.);"
           "vec3 p=normalize(r+y);"
           "float l=h(e,y,1.,1.),w=pow(clamp(dot(x,-p),0.,1.),1.),o=w*l;"
           "vec2 U;"
           "vec3 M=abs(y);"
           "if(M.x>M.y&&M.x>M.z)"
             "U=e.yz;"
           "else"
             " if(M.y>M.x&&M.y>M.z)"
               "U=e.xz;"
             "else"
               " if(M.z>M.y&&M.z>M.x)"
                 "U=e.xy;"
           "vec3 g=vec3(.1);"
           "if(_MapIndex==1)"
             "g=vec3(.1,0.,0.);"
           "i=g*(c+.25)+vec3(.7,.9,1.)*n;"
           "if(!a)"
             "{"
               "vec3 I=vec3(.2);"
               "if(_MapIndex==1)"
                 "I=vec3(.2,0.,0.);"
               "i+=I*o;"
               "i+=u(U);"
               "i*=b*k*t;"
             "}"
         "}"
     "}"
   "return i;"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "float x=.1,m=t(v)*x-x+_time;"
       "vec3 a=vec3(0.),i=vec3(0.);"
       "if(_MapIndex==0)"
         "a=vec3(0.,0.,1.5+m*20.),i=a+vec3(0.,0.,1.),i.xy+=f(i.z),a.xy+=f(a.z);"
       "else"
         " if(_MapIndex==1)"
           "a=vec3(cos(_time*.1)*5.,-1.,sin(_time*.1)*5.),i=vec3(0.,-2.,0.);"
       "vec3 d=a+vec3(0.,1.,5.);"
       "if(_MapIndex==0)"
         "d.xy+=f(d.z);"
       "float s=1.-.45*length(v),r=0.;"
       "vec3 e=vec3(0.),y=normalize(i-a),z=normalize(cross(vec3(0.,1.,0.),y)),b=normalize(cross(y,z)),c=normalize(v.x*z+v.y*b+s*y),n,k;"
       "bool p;"
       "{"
         "mapr M=f(a,c,false);"
         "vec3 h=(M.vPos-a-.5*sign(c))/c;"
         "r=max(max(h.x,h.y),h.z);"
         "e=f(a,c,r,M,d,false);"
         "k=a+c*r;"
         "n=-(M.mask*sign(c));"
         "p=M.hit;"
       "}"
       "if(p)"
         "{"
           "a=k;"
           "c=clamp(reflect(c,n),vec3(-.5),vec3(.5));"
           "mapr M=f(a,c,true);"
           "vec3 h=(M.vPos-a-.5*sign(c))/c;"
           "float u=max(max(h.x,h.y),h.z);"
           "u=clamp(u,0.,1.);"
           "e+=f(a,c,u,M,d,true);"
         "}"
       "vec3 h=mix(vec3(.96),vec3(.24),-c.y*.5+.5);"
       "if(_MapIndex==0)"
         "e=mix(e,h*sqrt(h)*1.2,smoothstep(0.,.95,r/60.));"
       "else"
         " if(_MapIndex==1)"
           "e=mix(e,h*sqrt(h)*1.2,smoothstep(0.,.95,r/120.));"
       "gl_FragColor=vec4(e,_Alpha);"
     "}"
 "}",

