R"(
uniform float _time;
uniform float _deltaTime;
uniform int _TrailNum;
uniform int _LineSegment;
uniform int _SegmentFuncIndex;

struct STrs
{
	vec4 pos;
	vec4 rot;
	vec4 scl;
	vec4 tan;
	ivec4 param; // ivec4(group, my_segment, now_segment, 0)
};

layout(std430, binding = SegmentBufferBinding) buffer in_trs_buffer
{
	STrs trs[];
} out_trs_buffer;

struct SGroup
{
	vec4 param; // vec4(now_segment, life, IsPermitUpdate, 0.0)
};

layout(std430, binding = GroupBufferBinding) buffer in_group_buffer
{
	SGroup group[];
} out_group_buffer;

float rand(vec2 st){
    return fract(
        sin(dot(st.xy,vec2(12.9898,78.233)))*43758.5453123
    );
}

void SphereTrail(inout STrs trs)
{
	float offsetA = rand(vec2(100.9123, 7.71562) * float(trs.param.x)) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * float(trs.param.x)) * 2.0 * 3.1415;
	//float r = 2.0;
	float r = 10.0;

	// 移動の乱数はgroup各に行う
	trs.pos = vec4(
		r*cos(_time+offsetA)*cos(_time+offsetB),
		r*cos(_time+offsetA)*sin(_time+offsetB),
		r*sin(_time+offsetA),
		1.0
	);
}

float hcys(float t,float rc,float rm,float rd){	return (rc-rm)*cos(t) + rd*cos( ((rc-rm)/rm) * t );}
float hcyc(float t,float rc,float rm,float rd){	return (rc-rm)*sin(t) - rd*sin( ((rc-rm)/rm) * t );}

void AuraTrail(inout STrs trs)
{
	float r = 1.0;
	//float r = 10.0;

	float offsetA = rand(vec2(100.9123, 7.71562) * float(trs.param.x)) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * float(trs.param.x)) * 2.0 * 3.1415;
	float Speed = 1.0;
	float rc = 3.0 * r, rm = 1.0 * r, rd = 2.0 * r, u = mod(_time*Speed + offsetA, 2.0*3.1415), v = mod(_time*Speed + offsetB, 2.0*3.1415);

	trs.pos = vec4(
		hcys(u, rc, rm, rd) * hcyc(v, rc, rm, rd),
		hcys(u, rc, rm, rd) * hcys(v, rc, rm, rd),
		hcyc(u, rc, rm, rd),
		1.0
	);

	/*float offsetA = rand(vec2(100.9123, 7.71562) * float(trs.param.x)) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * float(trs.param.x)) * 2.0 * 3.1415;
	float r = 1.0;
	//float r = 10.0;

	// 移動の乱数はgroup各に行う
	trs.pos = vec4(
		r*cos(_time*10.0+offsetA),
		2.0*r*cos(_time*10.0+offsetA),
		r*sin(_time*10.0+offsetA),
		1.0
	);*/
}

void CalTrailSegment(uvec3 DID)
{
	int id = int(DID.x);
	STrs trs = out_trs_buffer.trs[id];
	SGroup group = out_group_buffer.group[trs.param.x];

	int my_segment = trs.param.y; 
	
	if(my_segment == int(group.param.x) && int(group.param.z) == 1)
	{
		if(_SegmentFuncIndex == 0)
		{
			SphereTrail(trs);
		}
		else if(_SegmentFuncIndex == 1)
		{
			AuraTrail(trs);
		}
	}

	trs.param.z = int(group.param.x);
	//trs.param.w = int(floor(_time));

	out_trs_buffer.trs[id] = trs;
}

layout(local_size_x=NUMTHREAD, local_size_y=1, local_size_z=1) in;

void main()
{
	uvec3 DID = gl_GlobalInvocationID;
	CalTrailSegment(DID);
}

)"