R"(
uniform float _time;
uniform float _deltaTime;
uniform float _ParticleLife;
uniform int _TrailNum;
uniform int _LineSegment;

struct SGroup
{
	vec4 param; // vec4(now_segment, life, IsPermitUpdate, 0.0)
};

layout(std430, binding = GroupBufferBinding) buffer in_group_buffer
{
	SGroup group[];
} out_group_buffer;

float rand(vec2 st){
    return fract(
        sin(dot(st.xy,vec2(12.9898,78.233)))*43758.5453123
    );
}

void CalTrailGroup(uvec3 DID)
{
	int id = int(DID.x);
	SGroup group = out_group_buffer.group[id];
	group.param.y -= _deltaTime;

	if(group.param.y <= 0.0)
	{
		int now_segment = int(group.param.x);
		group.param.x  = float((now_segment  < _LineSegment - 1)? now_segment + 1 : 0);
		group.param.y = _ParticleLife;
		group.param.z = 1.0;
	}
	else
	{
		group.param.z = 0.0;
	}

	//group.param.w = floor(_time);

	out_group_buffer.group[id] = group;
}

layout(local_size_x=NUMTHREAD, local_size_y=1, local_size_z=1) in;

void main()
{
	uvec3 DID = gl_GlobalInvocationID;
	CalTrailGroup(DID);
}

)"