R"(
uniform float _time;
uniform float _deltaTime;
uniform int _TrailNum;
uniform int _LineSegment;
uniform int _SegmentFuncIndex;
uniform float _Radius;

#define rot(a) mat2(cos(a),sin(a),-sin(a),cos(a))
#define pi 3.14159265

struct STrs
{
	vec4 pos;
	vec4 rot;
	vec4 scl;
	vec4 tan;
	ivec4 param; // ivec4(group, my_segment, now_segment, 0)
};

layout(std430, binding = SegmentBufferBinding) buffer in_trs_buffer
{
	STrs trs[];
} out_trs_buffer;

struct SGroup
{
	vec4 param; // vec4(now_segment, life, IsPermitUpdate, 0.0)
};

layout(std430, binding = GroupBufferBinding) buffer in_group_buffer
{
	SGroup group[];
} out_group_buffer;

float rand(vec2 st){
    return fract(
        sin(dot(st.xy,vec2(12.9898,78.233)))*43758.5453123
    );
}

void SphereTrail(inout STrs trs)
{
	float offsetA = rand(vec2(100.9123, 7.71562) * float(trs.param.x)) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * float(trs.param.x)) * 2.0 * 3.1415;
	//float r = 2.0;
	float r = 10.0;

	// ˆÚ“®‚Ì—”‚ÍgroupŠe‚És‚¤
	trs.pos = vec4(
		r*cos(_time+offsetA)*cos(_time+offsetB),
		r*cos(_time+offsetA)*sin(_time+offsetB),
		r*sin(_time+offsetA),
		1.0
	);
}

float hcys(float t,float rc,float rm,float rd){	return (rc-rm)*cos(t) + rd*cos( ((rc-rm)/rm) * t );}
float hcyc(float t,float rc,float rm,float rd){	return (rc-rm)*sin(t) - rd*sin( ((rc-rm)/rm) * t );}

void AuraTrail(inout STrs trs,float id)
{
	/*int group = trs.param.x;
	float offsetA = rand(vec2(100.9123, 7.71562) * id) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * id) * 2.0 * 3.1415;

	 vec3 cen = vec3(0.0); float CenterPower = (group == 3 || group == 4 || group == 5)? 10.0 : 0.75, RotDir = 1.0;
	 if(group == 0 || group == 3)
	 {
		RotDir = (group == 3)? 1.0 : -1.0;
		cen = normalize(vec3(0.0, 1.0 * ((group>=3)? -1.0 : 1.0), 0.0)) * CenterPower;
	 }
	 else if(group == 1 || group == 4)
	 {
	    RotDir = -1.0;
		cen = normalize(vec3(-1.0, -1.0 * ((group>=3)? -1.0 : 1.0), 0.0)) * CenterPower;
	 }
	 else if(group == 2 || group == 5)
	 {
		RotDir = 1.0;
		cen = normalize(vec3(1.0, -1.0 * ((group>=3)? -1.0 : 1.0), 0.0)) * CenterPower;
	 }

	 vec3 s3d = vec3(1.0,(group > 2)? 10.0 : 1.0, 0.0);

	 // Scale
	 trs.pos = vec4(
		s3d.x*cos(_time * 25.0 * RotDir+offsetA) ,
		s3d.y*sin(_time * 25.0 * RotDir+offsetA),
		0.0,
		1.0
	);
	
	// Rotate
	if(group != 0 && group != 3) trs.pos.xz *= rot(pi/2.0);
	if(group != 0 && group != 3) trs.pos.xy *= rot( ((group == 1 || group == 5)? 1.0 : -1.0) * pi/4.0);

	// Translate
	trs.pos += vec4(cen, 0.0);*/

	/////////////////////////////////////
	float r = 1.0;
	//float r = 10.0;

	float offsetA = rand(vec2(100.9123, 7.71562) * float(trs.param.x)) * 2.0 * 3.1415;
	float offsetB = rand(vec2(6.601,80.123) * float(trs.param.x)) * 2.0 * 3.1415;
	float Speed = 1.0;
	float rc = 3.0 * r, rm = 1.0 * r, rd = 2.0 * r, u = mod(_time*Speed + offsetA, 2.0*3.1415), v = mod(_time*Speed + offsetB, 2.0*3.1415);

	trs.pos = vec4(
		hcys(u, rc, rm, rd) * hcyc(v, rc, rm, rd),
		hcys(u, rc, rm, rd) * hcys(v, rc, rm, rd),
		hcyc(u, rc, rm, rd),
		1.0
	);	
}

void CalTrailSegment(uvec3 DID)
{
	int id = int(DID.x);
	STrs trs = out_trs_buffer.trs[id];
	SGroup group = out_group_buffer.group[trs.param.x];

	int my_segment = trs.param.y; 
	
	if(my_segment == int(group.param.x) && int(group.param.z) == 1)
	{
		if(_SegmentFuncIndex == 0)
		{
			SphereTrail(trs);
		}
		else if(_SegmentFuncIndex == 1)
		{
			AuraTrail(trs, float(id));
		}
	}

	trs.param.z = int(group.param.x);
	//trs.param.w = int(floor(_time));

	out_trs_buffer.trs[id] = trs;
}

layout(local_size_x=NUMTHREAD, local_size_y=1, local_size_z=1) in;

void main()
{
	uvec3 DID = gl_GlobalInvocationID;
	CalTrailSegment(DID);
}

)"