/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\7_FeatherRobe\Shader\FeatherRobe_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter,_AuraPos;"
 "uniform sampler2D _BufferA;"
 "uniform float _Alpha;"
 "in vec2 uv;"
 "const float v=3.14159265;\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "const float y=3e-4,c=30.;"
 "const vec3 f=normalize(vec3(1.,1.,-1.));"
 "vec3 e;"
 "int i;"
 "float r;struct mapr{float d;bool hit;int m;float tvalue;float i;float acc;float neard;};"
 "void t(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<y)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<y)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 n(vec3 v,vec3 d,vec3 f,vec3 m)"
 "{"
   "return v+=m,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec3 n(vec3 v,vec3 d)"
 "{"
   "vec3 f=vec3(0.,0.,_time)+d;"
   "return f;"
 "}"
 "float n(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "const int m=50;"
 "const float d=.001,o=1.;"
 "vec2 n(vec2 v,vec2 d,vec2 m)"
 "{"
   "vec2 f=m-v,c=d-v;"
   "float y=clamp(dot(f,c)/dot(c,c),0.,1.);"
   "return vec2(dot(f-c*y,f-c*y),f.x*c.y-f.y*c.x);"
 "}"
 "float s(vec2 v,vec2 f,vec2 d,vec2 c)"
 "{"
   "vec2 m=min(min(n(v,f,c),n(f,d,c)),n(d,v,c));"
   "return-sqrt(m.x)*sign(m.y);"
 "}"
 "vec3 s(vec2 v,float d)"
 "{"
   "vec2 f=vec2(-.12,.1),c=vec2(.12,.1),m=vec2(0.,.4);"
   "float y=d*.1,r=min(1.,300.*s(c+vec2(y,-y),f+vec2(-y,-y),m+vec2(0.,y),v));"
   "if(r<0.)"
     "r=pow(smoothstep(0.,1.,abs(r*.05)),.1);"
   "r=max(.6,r);"
   "return vec3(r)*vec3(1.,.95,.975);"
 "}"
 "int n(const vec3 v,const vec3 f,const vec3 m,const vec3 n,const vec3 c,out float y)"
 "{"
   "vec3 r,i,e,x,t;"
   "float a,s,u,o,p;"
   "r=f-v;"
   "i=m-v;"
   "e=cross(c,i);"
   "a=dot(r,e);"
   "if(a>-d&&a<d)"
     "return 0;"
   "s=1./a;"
   "t=n-v;"
   "u=dot(t,e)*s;"
   "if(u<0.||u>1.)"
     "return 0;"
   "x=cross(t,r);"
   "o=dot(c,x)*s;"
   "if(o<0.||u+o>1.)"
     "return 0;"
   "p=dot(i,x)*s;"
   "if(p>d)"
     "return y=p,1;"
   "return 0;"
 "}"
 "int s(const vec3 v,const vec3 f,const vec3 m,const vec3 n,const vec3 c,out float y)"
 "{"
   "vec3 r,i,e,x,t;"
   "float a,s,u,o,p;"
   "r=f-v;"
   "i=m-v;"
   "e=cross(c,i);"
   "a=dot(r,e);"
   "if(a>-d&&a<d)"
     "return 0;"
   "s=1./a;"
   "t=n-v;"
   "u=dot(t,e)*s;"
   "x=cross(t,r);"
   "o=dot(c,x)*s;"
   "p=dot(i,x)*s;"
   "if(p>d)"
     "return y=p,1;"
   "return 0;"
 "}"
 "vec3 s(vec3 v,float f,float y)"
 "{"
   "float c=1.;"
   "v.z+=f;"
   "vec2 d=floor(v.xz),r=d+vec2(c,c);"
   "float m=.002,e=20.,i=5.,s=_time;"
   "s=1.;"
   "float t=sin(i*s+e*n(m*d)),x=sin(i*s+e*n(m*vec2(r.x,d.y))),o=sin(i*s+e*n(m*r)),u=sin(i*s+e*n(m*vec2(d.x,r.y))),p=.7*max(.3,min(1.,-(d.y-26.)*.05));"
   "vec3 a=vec3(d.x,t*p,d.y),z=vec3(r.x,x*p,d.y),b=vec3(r.x,o*p,r.y);"
   "float k,A,l,h;"
   "vec3 g=v+vec3(0.,100.,0.),C=vec3(0.,-1.,0.);"
   "int w=n(a,z,b,g,C,k);"
   "if(w==1)"
     "{"
       "vec3 W=g+C*k;"
       "return W;"
     "}"
   "vec3 W=g+C*A;"
   "return W;"
 "}"
 "mapr s(vec3 v)"
 "{"
   "mapr f;"
   "f.d=1e3;"
   "f.hit=false;"
   "f.m=-1;"
   "t(f,v.y-s(v,0.,1.).y*.75+3.,1,true);"
   "return f;"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "vec2 f=vec2(.001,0.);"
   "return normalize(vec3(s(v+f.xyy).d-s(v-f.xyy).d,s(v+f.yxy).d-s(v-f.yxy).d,s(v+f.yyx).d-s(v-f.yyx).d));"
 "}"
 "mapr t(vec3 v,vec3 f,const bool d)"
 "{"
   "mapr m;"
   "float e=0.,t=0.,i=0.;"
   "for(;++e<r;)"
     "{"
       "m=s(v+f*(t+=m.d*.75));"
       "if(m.d<y||m.tvalue>c)"
         "break;"
       "i+=exp(-3.*m.d);"
     "}"
   "m.i=e;"
   "m.tvalue=t;"
   "m.acc=i;"
   "return m;"
 "}"
 "mapr t(vec3 v,vec3 y)"
 "{"
   "mapr f;"
   "f.neard=1e3;"
   "float m=.25+n(vec2(99.99,4545.21)*5.)*1.25,c=1.,d=n(vec2(6.621,1.11148)*5.)*2.*3.1415,e=n(vec2(1.9987,.2259)*5.)*2.*3.1415;"
   "vec3 t=vec3(4.*m*cos(_time*c+d)*cos(_time*c+e),4.*m*cos(_time*c+d)*sin(_time*c+e),4.*m*sin(_time*c+d)),r=vec3(0.,2.,0.)+t;"
   "float s=0.,i=0.,p=0.;"
   "for(;++s<64.;)"
     "{"
       "f=mapr(length(v+y*(i+=f.d*.75)+r)-.25,false,2,0.,0.,0.,0.);"
       "if(f.d<f.neard)"
         "f.neard=f.d;"
       "if(f.d<.001)"
         "{"
           "f.hit=true;"
           "break;"
         "}"
       "if(f.d>1e3)"
         "break;"
       "p+=exp(-3.*f.d);"
     "}"
   "f.i=s;"
   "f.tvalue=i;"
   "f.acc=p;"
   "return f;"
 "}"
 "float x(vec3 f,vec3 v,float y)"
 "{"
   "return(-f.z+y)/v.z;"
 "}"
 "vec3 n(vec3 v,vec3 f,vec3 d,vec3 c,vec3 m,float y,float e)"
 "{"
   "vec3 r=normalize(reflect(m,d)),i=normalize(f-v);"
   "float t=dot(r,i),a=max(0.,t);"
   "vec3 o=vec3(a+.7),p=normalize(reflect(-i,c));"
   "float W=x(f,p,10.);"
   "vec3 n=f+p*W;"
   "float u=max(0.,t*2.);"
   "vec3 C=s(abs(n.xy)*vec2(.1,-.2)+vec2(0.,2.),e);"
   "return o*u+C*(1.-u);"
 "}"
 "float x(vec3 v,vec3 d)"
 "{"
   "float f=1.,i=0.;"
   "for(int r=0;r<5;r++)"
     "{"
       "float m=.15+float(r)*.15,c=s(d*m+v).d;"
       "i+=(m-c)*f;"
       "f*=.5;"
     "}"
   "return clamp(1.-i,0.,1.);"
 "}"
 "vec3 p(vec3 v,vec3 f,vec2 y)"
 "{"
   "vec3 m=vec3(.2,.2,.5)*.1;"
   "return m;"
 "}"
 "vec3 p(mapr v,vec3 m,vec3 y,vec2 d)"
 "{"
   "vec3 i=vec3(0.);"
   "if(v.hit)"
     "{"
       "vec3 c=m+y*v.tvalue,r=t(c),e=normalize(r+vec3(0.,8.,0.));"
       "if(v.m==0)"
         "{"
           "vec3 a=m+y*v.tvalue,p=t(a);"
           "float s=x(a,p),o=max(0.,dot(p,f));"
           "i=vec3(.2,.2,.5)*10./v.i*s*(o+.25);"
         "}"
       "else"
         " if(v.m==1)"
           "{"
             "vec3 s=vec3(1.,.95,.9);"
             "float a=abs(mod(c.x,1.)),p=abs(mod(c.z,1.)),o=60.,u=pow(a,o)+pow(1.-a,o)+pow(p,o)+pow(1.-p,o)+pow(1.-abs(a-p),o);"
             "u=max(0.,min(1.,u));"
             "vec3 W=n(m,c,r,e,f,-1.,1.)*s+u*4.*vec3(.917,.569,.596);"
             "i=vec3(exp(-.25*v.tvalue));"
             "float k=1.-length(d-vec2(0.,.25))*.5,z=max(0.,dot(r,f)),b=pow(max(0.,dot(reflect(-f,r),-y)),16.);"
             "i=vec3(.2,.2,.5)*.1*W*(z+.25)+vec3(1.)*b;"
             "i+=vec3(1.)*v.acc*.01;"
             "i*=k;"
           "}"
         "else"
           " if(v.m==2)"
             ";"
     "}"
   "return i;"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "vec3 f=_WorldCameraPos,c=_WorldCameraCenter,d=normalize(c-f),y=normalize(cross(vec3(0.,1.,0.),d)),s=normalize(cross(d,y)),e=normalize(v.x*y+v.y*s+d),i=p(f,e,v);"
       "r=128.;"
       "mapr m;"
       "m=t(f,e,false);"
       "if(m.hit)"
         "i=p(m,f,e,v);"
       "vec3 a=mix(vec3(.96),vec3(.24),-e.y*.5+.5);"
       "i=mix(i,a*sqrt(a)*1.2,smoothstep(0.,.95,m.tvalue/15.));"
       "mapr W=t(f,e);"
       "vec3 n=vec3(.917,.569,.596)*W.acc;"
       "i+=n;"
       "i+=texture(_BufferA,uv).xyz;"
       "gl_FragColor=vec4(i,_Alpha);"
     "}"
 "}",

