/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\7_FeatherRobe\Shader\FeatherRobe_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter,_AuraPos;"
 "uniform sampler2D _BufferA;"
 "uniform float _Alpha;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.001\n"
 "#define tmax 30.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\n"
 "vec3 v;"
 "int e;"
 "float f;struct mapr{float d;bool hit;int m;float tvalue;float i;float acc;float neard;};"
 "void t(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 n(vec3 v,vec3 d,vec3 f,vec3 m)"
 "{"
   "return v+=m,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec3 n(vec3 v,vec3 d)"
 "{"
   "vec3 f=vec3(0.,0.,_time)+d;"
   "return f;"
 "}"
 "float n(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}\n"
 "#define STEPS 50\n"
 "#define EPSILON 0.001\n"
 "#define BORDER_LINES\n"
 "#define BORDER_THICKNESS 1.0\n"
 "#define TRIANGLE_BG\n"
 "vec2 n(vec2 v,vec2 d,vec2 m)"
 "{"
   "vec2 f=m-v,c=d-v;"
   "float y=clamp(dot(f,c)/dot(c,c),0.,1.);"
   "return vec2(dot(f-c*y,f-c*y),f.x*c.y-f.y*c.x);"
 "}"
 "float s(vec2 v,vec2 f,vec2 d,vec2 c)"
 "{"
   "vec2 m=min(min(n(v,f,c),n(f,d,c)),n(d,v,c));"
   "return-sqrt(m.x)*sign(m.y);"
 "}"
 "vec3 s(vec2 v,float d)"
 "{"
   "\n#ifdef TRIANGLE_BG\n"
   "vec2 f=vec2(-.12,.1),c=vec2(.12,.1),m=vec2(0.,.4);"
   "float a=d*.1,r=min(1.,300.*s(c+vec2(a,-a),f+vec2(-a,-a),m+vec2(0.,a),v));"
   "if(r<0.)"
     "r=pow(smoothstep(0.,1.,abs(r*.05)),.1);"
   "r=max(.6,r);"
   "return vec3(r)*vec3(1.,.95,.975);"
 "}"
 "int n(const vec3 v,const vec3 d,const vec3 f,const vec3 m,const vec3 a,out float y)"
 "{"
   "vec3 c,r,i,e,t;"
   "float s,u,x,l,n;"
   "c=d-v;"
   "r=f-v;"
   "i=cross(a,r);"
   "s=dot(c,i);"
   "if(s>-EPSILON&&s<EPSILON)"
     "return 0;"
   "u=1./s;"
   "t=m-v;"
   "x=dot(t,i)*u;"
   "if(x<0.||x>1.)"
     "return 0;"
   "e=cross(t,c);"
   "l=dot(a,e)*u;"
   "if(l<0.||x+l>1.)"
     "return 0;"
   "n=dot(r,e)*u;"
   "if(n>EPSILON)"
     "return y=n,1;"
   "return 0;"
 "}"
 "int s(const vec3 v,const vec3 d,const vec3 f,const vec3 m,const vec3 a,out float y)"
 "{"
   "vec3 c,r,i,e,t;"
   "float s,u,x,l,n;"
   "c=d-v;"
   "r=f-v;"
   "i=cross(a,r);"
   "s=dot(c,i);"
   "if(s>-EPSILON&&s<EPSILON)"
     "return 0;"
   "u=1./s;"
   "t=m-v;"
   "x=dot(t,i)*u;"
   "e=cross(t,c);"
   "l=dot(a,e)*u;"
   "n=dot(r,e)*u;"
   "if(n>EPSILON)"
     "return y=n,1;"
   "return 0;"
 "}"
 "vec3 s(vec3 v,float d,float y)"
 "{"
   "float c=1.;"
   "v.z+=d;"
   "vec2 m=floor(v.xz),r=m+vec2(c,c);"
   "float f=.002,e=20.,a=5.;"
   "\n#ifdef FLAT_GROUND\n"
   "float t=0.,i=0.,l=0.,u=0.;"
   "\n#else\n"
   "float s=_time;"
   "s=1.;"
   "float x=sin(a*s+e*n(f*m)),z=sin(a*s+e*n(f*vec2(r.x,m.y))),o=sin(a*s+e*n(f*r)),b=sin(a*s+e*n(f*vec2(m.x,r.y)));"
   "\n#endif\n"
   "float T=.7*max(.3,min(1.,-(m.y-26.)*.05));"
   "vec3 B=vec3(m.x,x*T,m.y),A=vec3(r.x,z*T,m.y),p=vec3(r.x,o*T,r.y);"
   "float N,k,E,S;"
   "vec3 F=v+vec3(0.,100.,0.),h=vec3(0.,-1.,0.);"
   "int L=n(B,A,p,F,h,N);"
   "if(L==1)"
     "{"
       "vec3 I=F+h*N;"
       "return I;"
     "}"
   "vec3 I=F+h*k;"
   "return I;"
 "}"
 "mapr s(vec3 v)"
 "{"
   "mapr f;"
   "f.d=1e3;"
   "f.hit=false;"
   "f.m=-1;"
   "t(f,v.y-s(v,0.,1.).y*.75+3.,1,true);"
   "return f;"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "vec2 f=vec2(.001,0.);"
   "return normalize(vec3(s(v+f.xyy).d-s(v-f.xyy).d,s(v+f.yxy).d-s(v-f.yxy).d,s(v+f.yyx).d-s(v-f.yyx).d));"
 "}"
 "mapr t(vec3 v,vec3 d,const bool y)"
 "{"
   "mapr m;"
   "float e=0.,c=0.,r=0.;"
   "for(;++e<f;)"
     "{"
       "m=s(v+d*(c+=m.d*.75));"
       "if(m.d<dmin||m.tvalue>tmax)"
         "break;"
       "r+=exp(-3.*m.d);"
     "}"
   "m.i=e;"
   "m.tvalue=c;"
   "m.acc=r;"
   "return m;"
 "}"
 "mapr t(vec3 v,vec3 y)"
 "{"
   "mapr f;"
   "f.neard=1e3;"
   "float m=.25+n(vec2(99.99,4545.21)*5.)*1.25,c=1.,e=n(vec2(6.621,1.11148)*5.)*2.*3.1415,r=n(vec2(1.9987,.2259)*5.)*2.*3.1415;"
   "vec3 d=vec3(4.*m*cos(_time*c+e)*cos(_time*c+r),4.*m*cos(_time*c+e)*sin(_time*c+r),4.*m*sin(_time*c+e)),i=vec3(0.,2.,0.)+d;"
   "float t=0.,a=0.,s=0.;"
   "for(;++t<64.;)"
     "{"
       "f=mapr(length(v+y*(a+=f.d*.75)+i)-.25,false,2,0.,0.,0.,0.);"
       "if(f.d<f.neard)"
         "f.neard=f.d;"
       "if(f.d<.001)"
         "{"
           "f.hit=true;"
           "break;"
         "}"
       "if(f.d>1e3)"
         "break;"
       "s+=exp(-3.*f.d);"
     "}"
   "f.i=t;"
   "f.tvalue=a;"
   "f.acc=s;"
   "return f;"
 "}"
 "float m(vec3 v,vec3 f,float y)"
 "{"
   "return(-v.z+y)/f.z;"
 "}"
 "vec3 m(vec3 v,vec3 f,vec3 c,vec3 d,vec3 a,float y,float e)"
 "{"
   "\n#ifdef FLAT_SHADING\n"
   "f.xz=f.xz-mod(f.xz,1.);"
   "\n#endif\n"
   "vec3 r=normalize(reflect(a,c)),i=normalize(f-v);"
   "float t=dot(r,i),l=max(0.,t);"
   "vec3 x=vec3(l+.7),u=normalize(reflect(-i,d));"
   "float n=m(f,u,10.);"
   "vec3 I=f+u*n;"
   "float N=max(0.,t*2.);"
   "vec3 p=s(abs(I.xy)*vec2(.1,-.2)+vec2(0.,2.),e);"
   "return x*N+p*(1.-N);"
 "}"
 "float m(vec3 v,vec3 f)"
 "{"
   "float m=1.,c=0.;"
   "for(int r=0;r<5;r++)"
     "{"
       "float d=.15+float(r)*.15,e=s(f*d+v).d;"
       "c+=(d-e)*m;"
       "m*=.5;"
     "}"
   "return clamp(1.-c,0.,1.);"
 "}"
 "vec3 d(vec3 v,vec3 f,vec2 y)"
 "{"
   "vec3 m=vec3(.2,.2,.5)*.1;"
   "return m;"
 "}"
 "vec3 d(mapr v,vec3 f,vec3 d,vec2 a)"
 "{"
   "vec3 r=vec3(0.);"
   "if(v.hit)"
     "{"
       "vec3 c=f+d*v.tvalue,e=t(c),i=normalize(e+vec3(0.,8.,0.));"
       "if(v.m==0)"
         "{"
           "vec3 y=f+d*v.tvalue,x=t(y);"
           "float s=m(y,x),l=max(0.,dot(x,ldir));"
           "r=vec3(.2,.2,.5)*10./v.i*s*(l+.25);"
         "}"
       "else"
         " if(v.m==1)"
           "{"
             "vec3 s=vec3(1.,.95,.9);"
             "float y=abs(mod(c.x,1.)),x=abs(mod(c.z,1.)),l=60.,u=pow(y,l)+pow(1.-y,l)+pow(x,l)+pow(1.-x,l)+pow(1.-abs(y-x),l);"
             "u=max(0.,min(1.,u));"
             "vec3 n=m(f,c,e,i,ldir,-1.,1.)*s+u*4.*vec3(.917,.569,.596);"
             "r=vec3(exp(-.25*v.tvalue));"
             "float I=1.-length(a-vec2(0.,.25))*.5,z=max(0.,dot(e,ldir)),k=pow(max(0.,dot(reflect(-ldir,e),-d)),16.);"
             "r=vec3(.2,.2,.5)*.1*n*(z+.25)+vec3(1.)*k;"
             "r+=vec3(1.)*v.acc*.01;"
             "r*=I;"
           "}"
         "else"
           " if(v.m==2)"
             ";"
     "}"
   "return r;"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "vec3 c=_WorldCameraPos,r=_WorldCameraCenter,e=normalize(r-c),m=normalize(cross(vec3(0.,1.,0.),e)),s=normalize(cross(e,m)),y=normalize(v.x*m+v.y*s+e),i=d(c,y,v);"
       "f=128.;"
       "mapr a;"
       "a=t(c,y,false);"
       "if(a.hit)"
         "i=d(a,c,y,v);"
       "vec3 x=mix(vec3(.96),vec3(.24),-y.y*.5+.5);"
       "i=mix(i,x*sqrt(x)*1.2,smoothstep(0.,.95,a.tvalue/15.));"
       "mapr n=t(c,y);"
       "vec3 u=vec3(.917,.569,.596)*n.acc;"
       "i+=u;"
       "i+=texture(_BufferA,uv).xyz;"
       "gl_FragColor=vec4(i,_Alpha);"
     "}"
 "}",

